### ISSUE TITLE
[Repo cleanup] What kernels/devices do we need?

### ISSUE THREAD

**Issue by Strit** [manjaro-arm/packages-core#2]
What kernels do we need to build?
This is directly tied to what devices do we wish to support.

Please list the devices you would like to support from the ones in the repository now.
I'll start with my list:
* Raspberry Pi 3 (linux-raspberrypi)
* Odroid-C1(+) (linux-odroid-c1)
* Odroid-C2 (linux-odroid-c2)
* Odroid-XU4 (linux-odroid-xu3)

The kernels nobody wants to maintain/have maintained, will get removed from the repository.

**Comment by dodgejcr** [comment]
I still have the beaglebone black and beagleboard-xm laying around. Could support them if others want

**Comment by Strit** [comment]
What kernels is that?
Only the linux-am33x?

**Comment by dodgejcr** [comment]
yeah am33x and linux-armv7
